## Customizing Chromosome Organization

**Initializing**

initializeSex()
- allows setup for sexual model
- First 
- WF models:
  - top down parameter where male:total population ratio can be set:
```
sim.addSubpop ("p1", 500, 0.6)
#OR
p1. setSexRatio (0.6)
``` 
- Non WF models:
  - Offspring sex can be controlled, but overall ratio can't
```
p1.addCrossed(f, m, sex="M")
p1.addCrossed (f, m, sex=0.6)
```

Ex: Initializing sex chromosomes
- Need recombination rate for X because X chromosomes recombine in females
- Y chromosome is clonal so no recombination occurs
```
initializeChromosome(3, 1e6, "X", "X");
initializeGenomicElement(g1);
initializeMutationRate(1e-7);
initializeRecombinationRate(1e-8);

initializeChromosome(4, 1e6, "Y", "Y");
initializeGenomicElement(g1);
initializeMutationRate(1e-7);
```
  
initializeChromosome()
- (object<Chromosome>$)initializeChromosome(integer$ id, [Ni$ length = NULL], [string$ type = "A"], [Ns$ symbol = NULL], [Ns$ name = NULL], [integer$ mutationRuns = 0])
- id: number identification of chromosome
- length: base positions
- type: A (autosomal, diploid by default), H (haploid), X (diploid), Y (haploid)
- symbol: string symbol for chromosome
- Haploid means one haplosome per individual

Ex: Initializing two diploid autosomes
```
initialize() {
initializeMutationType("m1", 0.5, "f", 0.0);
initializeGenomicElementType("g1", m1, 1.0);

initializeChromosome(1, 1e5);
initializeGenomicElement(g1);
initializeMutationRate(1e-7);
initializeRecombinationRate(1e-8);

initializeChromosome(2, 7e4);
initializeGenomicElement(g1);
initializeMutationRate(1e-7);
initializeRecombinationRate(1e-8);
}
```

Ex: Using for loop
```
initialize() {
initializeSex();
initializeMutationType("m1", 0.5, "f", 0.0);
initializeGenomicElementType("g1", m1, 1.0);

for (id in 1:4, length in c(1e5, 7e4, 1e6, 1e6),
type in c("A", "A", "X", "Y"), symbol in c("A1", "A2", "X", "Y"))
{
initializeChromosome(id, length, type, symbol);
initializeGenomicElement(g1);
initializeMutationRate(1e-7);
initializeRecombinationRate(1e-8);
}
}
```

**Null Haplosomes**
- Placeholder for haplosomes that are not used

![null_haplosome](/Users/lanacheng/Documents/McCoy_Lab/Slim_notebook/Slim_lessons/images/null_haplosome.png)

Ex: Using eidos console to sample 1 male and 1 female
```
> p1.sampleIndividuals(1, sex="M").haplosomes
Haplosome<A:25> Haplosome<A:17> Haplosome<A:17> Haplosome<A:14>
Haplosome<X:75> Haplosome<X:null> Haplosome<Y:53>

> p1.sampleIndividuals(1, sex="F").haplosomes
Haplosome<A:17> Haplosome<A:21> Haplosome<A:10> Haplosome<A:12>
Haplosome<X:65> Haplosome<X:74> Haplosome<Y:null>
```

**Cloning**
WF:
- Create 1 haploid per individual
- setCloningRate(0.5) means half the offspring are generated by cloning and the other half is generated by biparental reproduction
```
initialize() {
initializeMutationType("m1", 0.5, "f", 0.0);
initializeGenomicElementType("g1", m1, 1.0);
initializeChromosome(1, 2e6, "H");
initializeGenomicElement(g1);
initializeMutationRate(1e-7);
initializeRecombinationRate(1e-8);
}

1 early() {
sim.addSubpop("p1", 2000);
p1.setCloningRate(0.5);
}
```

Non WF:
- Setting up overlapping generations
- Involves clonal reproduction of individuals and density dependent population regulation
```
initialize() {
defineConstant("K", 2000);
initializeSLiMModelType("nonWF");

initializeMutationType("m1", 0.5, "f", 0.0);
initializeGenomicElementType("g1", m1, 1.0);
m1.convertToSubstitution = T;

initializeChromosome(1, 2e6, "H");
initializeGenomicElement(g1);
initializeMutationRate(1e-7);
initializeRecombinationRate(1e-8);
}

reproduction()
{
p1.addCloned(individual);
}

1 early() {
sim.addSubpop("p1", K);
}

early() {
p1.fitnessScaling = K / p1.individualCount;
}

10000 late() { sim.outputFixedMutations(); }
```

- Non overlapping generations in Non WF:
  - To make reproduction stochastic, randomly choose 2000 parents with replacement from p1 and generate offspring.  
```
early() {
inds = sim.subpopulations.individuals;
inds[inds.age > 0].fitnessScaling = 0.0;
}

reproduction()
{
parents = p1.sampleIndividuals(K, replace=T);
for (parent in parents)
p1.addCloned(parent);

// we've done the reproduction for this tick, so deactivate ourselves
self.active = 0;
}
```


